CREATE TABLE "PLANT_INFO" (
	"P_ID"				int			NOT NULL	PRIMARY KEY,
	"P_NAME"			varchar(50)	NOT NULL,
	"P_SCI_NAME"		varchar(50)	NOT NULL,
	"ROOT_TYPE"			varchar(50),
	"ROOT_TYPE_AD"		varchar(50),
	"STEM_TYPE"			varchar(50),
	"STEM_TYPE_AE"		varchar(50),
	"STEM_TYPE_UN"		varchar(50),
	"LEAF_TYPE"			varchar(50),
	"LEAF_LEN"			varchar(50),
	"LEAF_VENE"			varchar(50),
	"LEAF_PHY"			varchar(50),
	"FLOWER_AES"		varchar(50),
	"FLOWER_POS"		varchar(50),
	"FLOWER_PLA"		varchar(50),
	"FLOWER_TYPE_CYM"	varchar(50),
	"FLOWER_TYPE_RAC"	varchar(50),
	"FLOWER_SYM_TYPE"	varchar(50),
	"SPORE_TYPE"		varchar(50),
	"FRUIT_CRE_TYPE"	varchar(50),
	"FRUIT_CHA_TYPE"	varchar(50),
	"FRUIT_TYPE_FLE"	varchar(50),
	"FRUIT_TYPE_DRY_DE"	varchar(50),
	"FRUIT_TYPE_DRY_IN"	varchar(50),
	"CHA_HEIGHT"		varchar(50),
	"CHA_PRICE"			varchar(50)
);

CREATE TABLE "ROOT_MED_PRO" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"ROOT_PRO"			varchar(50) NOT NULL,
	CONSTRAINT PK_ROOT_MED PRIMARY KEY ("P_ID","ROOT_PRO")
);

CREATE TABLE "STEM_MED_PRO" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"STEM_PRO"			varchar(50) NOT NULL,
	CONSTRAINT PK_STEM_MED PRIMARY KEY ("P_ID","STEM_PRO")
);

CREATE TABLE "LEAF_SHAPE" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"LEAF_SHA"			varchar(50) NOT NULL,
	CONSTRAINT PK_LEAF_SHAPE PRIMARY KEY ("P_ID","LEAF_SHA")
);

CREATE TABLE "LEAF_BASE" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"LEAF_BASE"			varchar(50) NOT NULL,
	CONSTRAINT PK_LEAF_BASE PRIMARY KEY ("P_ID","LEAF_BASE")
);

CREATE TABLE "LEAF_APEX" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"LEAF_APEX"			varchar(50) NOT NULL,
	CONSTRAINT PK_LEAF_APEX PRIMARY KEY ("P_ID","LEAF_APEX")
);

CREATE TABLE "LEAF_MARGIN" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"LEAF_MAR"			varchar(50) NOT NULL,
	CONSTRAINT PK_LEAF_MARGIN PRIMARY KEY ("P_ID","LEAF_MAR")
);

CREATE TABLE "LEAF_MED_PRO" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"LEAF_PRO"			varchar(50) NOT NULL,
	CONSTRAINT PK_LEAF_MED PRIMARY KEY ("P_ID","LEAF_PRO")
);

CREATE TABLE "FRUIT_MED_PRO" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"FRUIT_PRO"			varchar(50) NOT NULL,
	CONSTRAINT PK_FRUIT_MED PRIMARY KEY ("P_ID","FRUIT_PRO")
);

CREATE TABLE "FLOWER_TYPE" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"FLOWER_TYPE"		varchar(50) NOT NULL,
	CONSTRAINT PK_FLOWER_TYPE PRIMARY KEY ("P_ID","FLOWER_TYPE")
);

CREATE TABLE "FLOWER_SEX_TYPE" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"FLOWER_SEX_TYPE"	varchar(50) NOT NULL,
	CONSTRAINT PK_FLOWER_SEX_TYPE PRIMARY KEY ("P_ID","FLOWER_SEX_TYPE")
);

CREATE TABLE "FLOWER_PE_COLOR" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"FLOWER_PE_COLOR"	varchar(50) NOT NULL,
	CONSTRAINT PK_FLOWER_PE_COLOR PRIMARY KEY ("P_ID","FLOWER_PE_COLOR")
);

CREATE TABLE "FLOWER_MED_PRO" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"FLOWER_PRO"		varchar(50) NOT NULL,
	CONSTRAINT PK_FLOWER_MED PRIMARY KEY ("P_ID","FLOWER_PRO")
);

CREATE TABLE "CHA_LOCATION" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"CHA_LOC"			varchar(50) NOT NULL,
	CONSTRAINT PK_CHA_LOCATION PRIMARY KEY ("P_ID","CHA_LOC")
);

CREATE TABLE "CHA_TOXICITY" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"CHA_TOXIC"			varchar(50) NOT NULL,
	CONSTRAINT PK_CHA_TOXICITY PRIMARY KEY ("P_ID","CHA_TOXIC")
);

CREATE TABLE "EN_MOIST" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"EN_MOIST"			varchar(50) NOT NULL,
	CONSTRAINT PK_EN_MOIST PRIMARY KEY ("P_ID","EN_MOIST")
);

CREATE TABLE "EN_TEMPERATURE" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"EN_TEM"			varchar(50) NOT NULL,
	CONSTRAINT PK_EN_TEMPERATURE PRIMARY KEY ("P_ID","EN_TEM")
);

CREATE TABLE "EN_ILLUMINATION" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"EN_ILLU"			varchar(50) NOT NULL,
	CONSTRAINT PK_EN_ILLUMINATION PRIMARY KEY ("P_ID","EN_ILLU")
);

CREATE TABLE "EN_SOIL_NUTRITION" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"EN_SOIL_NUTRI"		varchar(50) NOT NULL,
	CONSTRAINT PK_EN_SOIL_NUTRITION PRIMARY KEY ("P_ID","EN_SOIL_NUTRI")
);

CREATE TABLE "EN_SOIL_PH" (
	"P_ID"				int			NOT NULL	REFERENCES "PLANT_INFO"("P_ID"),
	"EN_SOIL_PH"		varchar(50) NOT NULL,
	CONSTRAINT PK_EN_SOIL_PH PRIMARY KEY ("P_ID","EN_SOIL_PH")
);